version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  user_service:
    # image: lekhaaakash/user_service:latest
    # platform: linux/arm64
    build: ./user_service
    ports:
      - "5001:5001"
    volumes:
      - ./common:/app/common
    environment:
      - JWT_SECRET_KEY=your-secret-key
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      mysql:
        condition: service_healthy

  product_service:
    # image: lekhaaakash/product_service:latest
    # platform: linux/arm64
    build: ./product_service
    expose:
      - "5002"
    volumes:
      - ./common:/app/common
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
    depends_on:
      mysql:
        condition: service_healthy

  cart_service:
    # image: lekhaaakash/cart_service:latest
    # platform: linux/arm64
    build: ./cart_service
    expose:
      - "5003"
    volumes:
      - ./common:/app/common
    environment:
      - JWT_SECRET_KEY=your-secret-key
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=ecommerce
      - PRODUCT_SERVICE_URL=http://product_service:5002
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user_service
      - product_service
      - cart_service

volumes:
  mysql_data:

networks:
  ecommerce-network:
    driver: bridge