name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push User service image
        run: |
          cd user_service
          docker build -t $DOCKER_HUB_USERNAME/user_service:latest .
          docker push $DOCKER_HUB_USERNAME/user_service:latest

      - name: Build and push Product service image
        run: |
          cd product_service
          docker build -t $DOCKER_HUB_USERNAME/product_service:latest .
          docker push $DOCKER_HUB_USERNAME/product_service:latest

      - name: Build and push Cart service image
        run: |
          cd cart_service
          docker build -t $DOCKER_HUB_USERNAME/cart_service:latest .
          docker push $DOCKER_HUB_USERNAME/cart_service:latest
          
      - name: Build and push API Gateway service image
        run: |
          cd api_gateway
          docker build -t $DOCKER_HUB_USERNAME/api_gateway:latest .
          docker push $DOCKER_HUB_USERNAME/api_gateway:latest
